# app/core/games/game_registry.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


class GameValidationError(ValueError):
    """The submitted create/turn payload is structurally invalid."""


GameState = dict[str, Any]
TurnActionData = dict[str, Any]
TurnApplicationResult = dict[str, Any]


@dataclass(frozen=True)
class GameDefinition:
    game_type: str
    label: str

    create_initial_state: Callable[[dict[str, Any] | None], GameState]

    # Applies either an Ed/frontend turn or Iris/prepared-choice turn.
    apply_turn: Callable[
        [GameState, dict[str, Any] | None, TurnActionData, str],
        TurnApplicationResult,
    ]

    # Builds prompt-facing game context from the durable session.
    build_context_display: Callable[
        [GameState, dict[str, Any] | None],
        dict[str, Any],
    ]


# ---------------------------------------------------------------------------
# Generic validation helpers
# ---------------------------------------------------------------------------

def _require_nonempty_string(
    value: Any,
    field_name: str,
) -> str:
    if not isinstance(value, str) or not value.strip():
        raise GameValidationError(
            f"{field_name} must be a non-empty string."
        )

    return value.strip()


def _validate_chess_state(state: Any) -> GameState:
    """
    V1 deliberately trusts chess.js as the rules authority.

    We validate the durable shape, but do not independently parse or prove
    chess legality/FEN validity in Python.
    """
    if not isinstance(state, dict):
        raise GameValidationError("Chess state must be an object.")

    fen = _require_nonempty_string(
        state.get("fen"),
        "Chess state.fen",
    )

    muse_plan = state.get("muse_plan")

    if muse_plan is not None and not isinstance(muse_plan, str):
        raise GameValidationError(
            "Chess state.muse_plan must be a string or null."
        )

    return {
        "fen": fen,
        "muse_plan": muse_plan,
    }


def _validate_prepared_muse_turn(
    prepared: Any,
    *,
    prepared_for_revision: int,
) -> dict[str, Any]:
    """
    This is generated by chess.js after User's move.

    `context_display` is Muse-visible:
      current board ASCII, side to move, legal moves, etc.

    `transitions` is backend-only:
      legal move -> resulting next_state.
    """
    if not isinstance(prepared, dict):
        raise GameValidationError(
            "prepare_muse_turn must be an object."
        )

    context_display = prepared.get("context_display")
    transitions = prepared.get("transitions")

    if not isinstance(context_display, dict):
        raise GameValidationError(
            "prepare_muse_turn.context_display must be an object."
        )

    if not isinstance(transitions, list) or not transitions:
        raise GameValidationError(
            "prepare_muse_turn.transitions must be a non-empty list."
        )

    normalized_transitions: list[dict[str, Any]] = []
    seen_moves: set[str] = set()

    for index, transition in enumerate(transitions):
        if not isinstance(transition, dict):
            raise GameValidationError(
                f"Prepared chess transition {index} must be an object."
            )

        move = _require_nonempty_string(
            transition.get("move"),
            f"Prepared chess transition {index}.move",
        )

        if move in seen_moves:
            raise GameValidationError(
                f"Prepared chess move '{move}' appears more than once."
            )

        seen_moves.add(move)

        next_state = _validate_chess_state(
            transition.get("next_state")
        )

        san = transition.get("san")
        if san is not None and not isinstance(san, str):
            raise GameValidationError(
                f"Prepared chess transition {index}.san "
                "must be a string or null."
            )

        normalized_transitions.append({
            "move": move,
            "san": san,
            "next_state": next_state,
        })

    return {
        "prepared_for_revision": prepared_for_revision,
        "prepared_for_actor": "muse",
        "context_display": context_display,
        "transitions": normalized_transitions,
    }


# ---------------------------------------------------------------------------
# Chess
# ---------------------------------------------------------------------------

def create_chess_initial_state(
    create_data: dict[str, Any] | None,
) -> GameState:
    """
    Chess v1 begins with User to move.

    The frontend supplies the standard starting FEN or an explicitly chosen
    setup FEN. No backend chess parser is involved in this version.
    """
    create_data = create_data or {}

    return _validate_chess_state({
        "fen": create_data.get(
            "fen",
            "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/"
            "RNBQKBNR w KQkq - 0 1",
        ),
        "muse_plan": create_data.get("muse_plan"),
    })


def apply_chess_turn(
    current_state: GameState,
    pending_muse_turn: dict[str, Any] | None,
    action_data: TurnActionData,
    actor_role: str,
) -> TurnApplicationResult:
    """
    Two intentionally different ingress paths:

    user:
      frontend/chess.js supplies resulting next_state plus prepared legal
      Muse transitions for the newly committed position.

    muse:
      Muse chooses one move from the currently stored prepared transitions.
      Backend looks up its precomputed resulting state.
    """
    current_state = _validate_chess_state(current_state)

    operation = action_data.get("operation")
    if not isinstance(operation, dict):
        raise GameValidationError("Chess action requires operation object.")

    move = _require_nonempty_string(
        operation.get("move"),
        "Chess operation.move",
    )

    if actor_role == "user":
        if pending_muse_turn is not None:
            raise GameValidationError(
                "Chess is waiting for Iris to take the prepared turn."
            )

        next_state = _validate_chess_state(
            action_data.get("next_state")
        )

        expected_next_revision = action_data["expected_revision"] + 1

        prepared_muse_turn = _validate_prepared_muse_turn(
            action_data.get("prepare_muse_turn"),
            prepared_for_revision=expected_next_revision,
        )

        ui_display = action_data.get("ui_display") or {}

        return {
            "state": next_state,
            "pending_muse_turn": prepared_muse_turn,
            "turn_result": {
                "move": move,
                "notation": ui_display.get("notation"),
                "actor": "user",
            },
        }

    if actor_role == "muse":
        if pending_muse_turn is None:
            raise GameValidationError(
                "Chess has no prepared Muse turn to consume."
            )

        if "muse_plan" not in operation:
            raise GameValidationError(
                "Muse chess turns must explicitly include muse_plan. "
                "Use null to intentionally clear it."
            )

        muse_plan = operation["muse_plan"]
        if muse_plan is not None and not isinstance(muse_plan, str):
            raise GameValidationError(
                "Muse chess operation.muse_plan must be a string or null."
            )

        transition = next(
            (
                item
                for item in pending_muse_turn["transitions"]
                if item["move"] == move
            ),
            None,
        )

        if transition is None:
            raise GameValidationError(
                f"Chess move '{move}' is not among the prepared legal moves."
            )

        next_state = {
            **transition["next_state"],
            "muse_plan": muse_plan,
        }

        return {
            "state": next_state,
            "pending_muse_turn": None,
            "turn_result": {
                "move": move,
                "notation": transition.get("san"),
                "actor": "muse",
            },
        }

    raise GameValidationError(
        f"Unsupported chess actor_role '{actor_role}'."
    )


def build_chess_context_display(
    state: GameState,
    pending_muse_turn: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    If it is Muse's prepared turn, expose the rich frontend-produced board
    context. Crucially, do NOT expose each successor's next_state/FEN.

    If it is User's turn, basic state is enough; his browser owns local move
    interaction and will prepare Muse's options after their next move.
    """
    state = _validate_chess_state(state)

    result = {
        "fen": state["fen"],
        "muse_plan": state["muse_plan"],
        "muse_turn_prepared": pending_muse_turn is not None,
    }

    if pending_muse_turn is not None:
        result.update(pending_muse_turn["context_display"])

    return result


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

GAME_TYPES: dict[str, GameDefinition] = {
    "chess": GameDefinition(
        game_type="chess",
        label="Chess",
        create_initial_state=create_chess_initial_state,
        apply_turn=apply_chess_turn,
        build_context_display=build_chess_context_display,
    ),
}


def get_game_definition(game_type: str) -> GameDefinition:
    try:
        return GAME_TYPES[game_type]
    except KeyError as exc:
        raise GameValidationError(
            f"Unsupported game_type '{game_type}'."
        ) from exc


def list_game_definitions() -> list[dict[str, str]]:
    return [
        {
            "game_type": definition.game_type,
            "label": definition.label,
        }
        for definition in GAME_TYPES.values()
    ]