# app/core/games/game_registry.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


class GameValidationError(ValueError):
    """The submitted create/turn payload is structurally invalid."""


GameState = dict[str, Any]
TurnActionData = dict[str, Any]
TurnApplicationResult = dict[str, Any]


@dataclass(frozen=True)
class GameDefinition:
    game_type: str
    label: str


    create_initial_state: Callable[[dict[str, Any] | None], GameState]

    # Applies either an Ed/frontend turn or Iris/prepared-choice turn.
    apply_turn: Callable[
        [GameState, dict[str, Any] | None, TurnActionData, str],
        TurnApplicationResult,
    ]

    # Builds prompt-facing game context from the durable session.
    build_context_display: Callable[
        [GameState, dict[str, Any] | None],
        dict[str, Any],
    ]

    # Converts the safe context_display projection into hidden prompt text.
    render_prompt_context: Callable[[dict[str, Any], bool], str | None] | None = None

    # Turns a committed turn receipt from message_metadata into a compact
    # hidden Recent Conversation/history block.
    render_turn_action_history: Callable[
        [dict[str, Any]],
        str | None,
    ] | None = None

    has_board: bool = False

# ---------------------------------------------------------------------------
# Generic validation helpers
# ---------------------------------------------------------------------------

def _require_nonempty_string(
    value: Any,
    field_name: str,
) -> str:
    if not isinstance(value, str) or not value.strip():
        raise GameValidationError(
            f"{field_name} must be a non-empty string."
        )

    return value.strip()


def _validate_chess_state(state: Any) -> GameState:
    """
    V1 deliberately trusts chess.js as the rules authority.

    We validate the durable shape, but do not independently parse or prove
    chess legality/FEN validity in Python.
    """
    if not isinstance(state, dict):
        raise GameValidationError("Chess state must be an object.")

    fen = _require_nonempty_string(
        state.get("fen"),
        "Chess state.fen",
    )

    muse_plan = state.get("muse_plan")

    if muse_plan is not None and not isinstance(muse_plan, str):
        raise GameValidationError(
            "Chess state.muse_plan must be a string or null."
        )

    return {
        "fen": fen,
        "muse_plan": muse_plan,
    }


def _validate_prepared_muse_turn(
    prepared: Any,
    *,
    prepared_for_revision: int,
) -> dict[str, Any]:
    """
    This is generated by chess.js after User's move.

    `context_display` is Muse-visible:
      current board ASCII, side to move, legal moves, etc.

    `transitions` is backend-only:
      legal move -> resulting next_state.
    """
    if not isinstance(prepared, dict):
        raise GameValidationError(
            "prepare_muse_turn must be an object."
        )

    context = prepared.get("context")
    transitions = prepared.get("transitions")

    if not isinstance(context, dict):
        raise GameValidationError(
            "prepare_muse_turn.context must be an object."
        )

    if not isinstance(transitions, list):
        raise GameValidationError(
            "prepare_muse_turn.transitions must be a list."
        )

    normalized_transitions: list[dict[str, Any]] = []
    seen_moves: set[str] = set()

    for index, transition in enumerate(transitions):
        if not isinstance(transition, dict):
            raise GameValidationError(
                f"Prepared chess transition {index} must be an object."
            )

        move = _require_nonempty_string(
            transition.get("move"),
            f"Prepared chess transition {index}.move",
        )

        if move in seen_moves:
            raise GameValidationError(
                f"Prepared chess move '{move}' appears more than once."
            )

        seen_moves.add(move)

        next_state = _validate_chess_state(
            transition.get("next_state")
        )

        san = transition.get("san")
        if san is not None and not isinstance(san, str):
            raise GameValidationError(
                f"Prepared chess transition {index}.san "
                "must be a string or null."
            )

        narration = transition.get("narration")
        if narration is not None and not isinstance(narration, str):
            raise GameValidationError(
                f"Prepared chess transition {index}.narration "
                "must be a string or null."
            )

        after_ascii = transition.get("after_ascii")
        if after_ascii is not None and not isinstance(after_ascii, str):
            raise GameValidationError(
                f"Prepared chess transition {index}.after_ascii "
                "must be a string or null."
            )

        normalized_transitions.append({
            "move": move,
            "san": san,
            "next_state": next_state,
            "narration": narration,
            "after_ascii": after_ascii,
        })

    return {
        "prepared_for_revision": prepared_for_revision,
        "prepared_for_actor": "muse",
        "context": context,
        "transitions": normalized_transitions,
    }


# ---------------------------------------------------------------------------
# Chess
# ---------------------------------------------------------------------------

def create_chess_initial_state(
    create_data: dict[str, Any] | None,
) -> GameState:
    """
    Chess v1 begins with User to move.

    The frontend supplies the standard starting FEN or an explicitly chosen
    setup FEN. No backend chess parser is involved in this version.
    """
    create_data = create_data or {}

    return _validate_chess_state({
        "fen": create_data.get(
            "fen",
            "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/"
            "RNBQKBNR w KQkq - 0 1",
        ),
        "muse_plan": create_data.get("muse_plan"),
    })


def apply_chess_turn(
    current_state: GameState,
    pending_muse_turn: dict[str, Any] | None,
    action_data: TurnActionData,
    actor_role: str,
) -> TurnApplicationResult:
    """
    Two intentionally different ingress paths:

    user:
      frontend/chess.js supplies resulting next_state plus prepared legal
      Muse transitions for the newly committed position.

    muse:
      Muse chooses one move from the currently stored prepared transitions.
      Backend looks up its precomputed resulting state.
    """
    current_state = _validate_chess_state(current_state)

    operation = action_data.get("operation")
    if not isinstance(operation, dict):
        raise GameValidationError("Chess action requires operation object.")

    move = _require_nonempty_string(
        operation.get("move"),
        "Chess operation.move",
    )

    if actor_role == "user":
        if pending_muse_turn is not None:
            raise GameValidationError(
                "Chess is waiting for Iris to take the prepared turn."
            )

        next_state = _validate_chess_state(
            action_data.get("next_state")
        )

        expected_next_revision = action_data["expected_revision"] + 1

        prepared_muse_turn = _validate_prepared_muse_turn(
            action_data.get("prepare_muse_turn"),
            prepared_for_revision=expected_next_revision,
        )

        message_metadata = action_data.get("message_metadata") or {}

        return {
            "state": next_state,
            "pending_muse_turn": prepared_muse_turn,
            "turn_result": {
                "move": move,
                "narration": message_metadata.get("narration"),
                "actor": "user",
                "message_metadata": message_metadata,
            },
        }

    if actor_role == "muse":
        if pending_muse_turn is None:
            raise GameValidationError(
                "Chess has no prepared Muse turn to consume."
            )

        if "muse_plan" not in operation:
            raise GameValidationError(
                "Muse chess turns must explicitly include muse_plan. "
                "Use null to intentionally clear it."
            )

        muse_plan = operation["muse_plan"]
        if muse_plan is not None and not isinstance(muse_plan, str):
            raise GameValidationError(
                "Muse chess operation.muse_plan must be a string or null."
            )

        transition = next(
            (
                item
                for item in pending_muse_turn["transitions"]
                if item["move"] == move
            ),
            None,
        )

        if transition is None:
            raise GameValidationError(
                f"Chess move '{move}' is not among the prepared legal moves."
            )

        next_state = {
            **transition["next_state"],
            "muse_plan": muse_plan,
        }

        message_metadata = {
            "action_type": "take_game_turn",
            "game_id": action_data.get("game_id"),
            "game_type": "chess",
            "turn_number": pending_muse_turn.get("prepared_for_revision") + 1,
            "narration": transition.get("narration"),
            "table": {
                "side": pending_muse_turn.get("context", {}).get("side_to_move"),
                "board_ascii": transition.get("after_ascii"),
                "fen": next_state.get("fen"),
            }
        }

        return {
            "state": next_state,
            "pending_muse_turn": None,
            "turn_result": {
                "move": move,
                "narration": transition.get("narration"),
                "actor": "muse",
                "message_metadata": message_metadata,
            },
        }

    raise GameValidationError(
        f"Unsupported chess actor_role '{actor_role}'."
    )


def build_chess_context_display(
    state: GameState,
    pending_muse_turn: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    If it is Muse's prepared turn, expose the rich frontend-produced board
    context. Crucially, do NOT expose each successor's next_state/FEN.

    If it is User's turn, basic state is enough; the browser owns local move
    interaction and will prepare Muse's options after their next move.
    """
    state = _validate_chess_state(state)

    result = {
        "fen": state["fen"],
        "muse_plan": state["muse_plan"],
        "muse_turn_prepared": pending_muse_turn,
    }

    if pending_muse_turn is not None:
        result.update(pending_muse_turn["context"])

    return result

def render_chess_prompt_context(
    context: dict[str, Any] | None,
    game_panel_open: bool = False,
) -> str | None:
    if not context:
        return None

    muse_turn_prepared = bool(context.get("muse_turn_prepared"))

    # No active shared board awareness, and no Muse turn to take.
    if not muse_turn_prepared and not game_panel_open:
        return None

    lines = [
        "[GAME CONTEXT: CHESS]",
        "",
        f"Current board FEN: {context['fen']}",

        "",
        "Current strategic plan:",
        context.get("muse_plan") or "(No active plan.)",
        "",
        "Board:",
        context["ascii"],
    ]

    lines.extend([
        "",
        f"Last move: {context.get('preceding_move_narration') or '(Unavailable.)'}",
    ])

    if muse_turn_prepared:
        legal_moves = context.get("legal_moves", [])
        legal_move_keys = [
            entry["move"]
            for entry in legal_moves
            if entry.get("move")
        ]

        if legal_move_keys:
            lines.extend([
                "",
                "Legal moves (UCI):",
                " ".join(legal_move_keys),
                "",
                f"Side to move: {context['side_to_move']}",
                "",
                "It is your turn. Choose exactly one move from the legal-move list.",
                "",
                "Play as a thoughtful, fallible human opponent—not a chess engine.",
                "Before choosing, consider more than the move that looks immediately attractive:",
                "- immediate threats, captures, checks, and tactical replies;",
                "- king safety and loose or overloaded pieces;",
                "- development, activity, and control of important squares;",
                "- pawn structure and whether the move creates a lasting weakness;",
                "- what Ed is likely trying to achieve on the following move;",
                "- whether your move supports a coherent plan for the next few turns.",
                "",
                "Do that evaluation internally. In your visible table-talk, you may be concise,",
                "playful, or strategic—but do not claim engine certainty or reveal hidden analysis.",
                "",
                "When taking your turn, you must explicitly do one of the following "
                "with your muse_plan:",
                "- replace the previous plan;",
                "- revise it;",
                "- reaffirm it in updated wording; or",
                "- clear it with null.",
                "",
                "Do not leave a previous plan silently unchanged.",
                "",
                (
                    'Emit: [COMMAND: take_game_turn] '
                    '{"move": "<exact UCI legal move>", '
                    '"muse_plan": "<replace, revise, or reaffirm your plan; or null>"} '
                    '[/COMMAND]'
                ),
            ])
        else:
            lines.extend([
                "",
                "There are no legal moves. The game is over.",
                "Do not emit a take_game_turn command.",
            ])
    else:
        lines.extend([
            "",
            "Ed currently has the chess panel open. You are sharing awareness of the",
            "ongoing game, but this is not an instruction to take a move.",
            "",
            "It is Ed's turn. Do not choose or emit a chess move.",
            "You may naturally acknowledge or discuss the board if it is relevant to",
            "the conversation, but do not interrupt unrelated conversation to comment on it.",
        ])

    lines.append("[/GAME CONTEXT: CHESS]")
    return "\n".join(lines)

def render_chess_turn_action_history(
    action: dict[str, Any],
) -> str | None:
    table = action.get("table") or {}

    narration = action.get("narration")
    fen = action.get("fen")

    if not narration and not fen:
        return None

    lines = ["[GAME HISTORY: CHESS]"]

    if narration:
        lines.extend(["", narration])

    if fen:
        lines.extend(f"Fen: {fen}")

    # Optional compact board snapshot—not a full active-table packet.
    if table.get("board_ascii"):
        lines.extend([
            "",
            "Board after move:",
            table["board_ascii"],
        ])

    return "\n".join(lines)

# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

GAME_TYPES: dict[str, GameDefinition] = {
    "chess": GameDefinition(
        game_type="chess",
        label="Chess",
        has_board=True,
        create_initial_state=create_chess_initial_state,
        apply_turn=apply_chess_turn,
        build_context_display=build_chess_context_display,
        render_prompt_context=render_chess_prompt_context,
        render_turn_action_history=render_chess_turn_action_history,
    ),
}


def get_game_definition(game_type: str) -> GameDefinition:
    try:
        return GAME_TYPES[game_type]
    except KeyError as exc:
        raise GameValidationError(
            f"Unsupported game_type '{game_type}'."
        ) from exc


def list_game_definitions() -> list[dict[str, str]]:
    return [
        {
            "game_type": definition.game_type,
            "label": definition.label,
        }
        for definition in GAME_TYPES.values()
    ]